/*!
* \file   ModCamClay_semiExpl_coupled.cxx
* \brief  this file implements the ModCamClay_semiExpl_coupled Behaviour.
*         File generated by tfel version 4.2.4-dev
* \author Aqeel Afzal Chaudhry , Christian Silbermann , Eric Simo , Miguel Mánica , Thomas Helfer , Thomas Nagel
* \date   01 / 09 / 2025
 */

#include<string>
#include<cstring>
#include<sstream>
#include<fstream>
#include<stdexcept>

#include"TFEL/Raise.hxx"
#include"TFEL/Material/ModCamClay_semiExpl_coupledBehaviourData.hxx"
#include"TFEL/Material/ModCamClay_semiExpl_coupledIntegrationData.hxx"
#include"TFEL/Material/ModCamClay_semiExpl_coupled.hxx"

namespace tfel::material{

ModCamClay_semiExpl_coupledParametersInitializer&
ModCamClay_semiExpl_coupledParametersInitializer::get()
{
static ModCamClay_semiExpl_coupledParametersInitializer i;
return i;
}

ModCamClay_semiExpl_coupledParametersInitializer::ModCamClay_semiExpl_coupledParametersInitializer()
{
this->theta = 1;
this->epsilon = 1e-14;
this->iterMax = 100;
this->minimal_time_step_scaling_factor = 0.1;
this->maximal_time_step_scaling_factor = 1.7976931348623e+308;
this->numerical_jacobian_epsilon = 1e-15;
// Reading parameters from a file
ModCamClay_semiExpl_coupledParametersInitializer::readParameters(*this,"ModCamClay_semiExpl_coupled-parameters.txt");
}

void
ModCamClay_semiExpl_coupledParametersInitializer::set(const char* const key,
const double v){
using namespace std;
if(::strcmp("theta",key)==0){
this->theta = v;
} else if(::strcmp("epsilon",key)==0){
this->epsilon = v;
} else if(::strcmp("minimal_time_step_scaling_factor",key)==0){
this->minimal_time_step_scaling_factor = v;
} else if(::strcmp("maximal_time_step_scaling_factor",key)==0){
this->maximal_time_step_scaling_factor = v;
} else if(::strcmp("numerical_jacobian_epsilon",key)==0){
this->numerical_jacobian_epsilon = v;
} else {
tfel::raise("ModCamClay_semiExpl_coupledParametersInitializer::set: "
" no parameter named '"+std::string(key)+"'");
}
}

void
ModCamClay_semiExpl_coupledParametersInitializer::set(const char* const key,
const unsigned short v){
using namespace std;
if(::strcmp("iterMax",key)==0){
this->iterMax = v;
} else {
tfel::raise("ModCamClay_semiExpl_coupledParametersInitializer::set: "
"no parameter named '"+std::string(key)+"'");
}
}

double
ModCamClay_semiExpl_coupledParametersInitializer::getDouble(const std::string& n,
const std::string& v)
{
double value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ModCamClay_semiExpl_coupledParametersInitializer::getDouble: "
"can't convert '"+v+"' to double for parameter '"+ n+"'");
return value;
}

unsigned short
ModCamClay_semiExpl_coupledParametersInitializer::getUnsignedShort(const std::string& n,
const std::string& v)
{
unsigned short value;
std::istringstream converter(v);
converter >> value;
tfel::raise_if(!converter||(!converter.eof()),
"ModCamClay_semiExpl_coupledParametersInitializer::getUnsignedShort: "
"can't convert '"+v+"' to unsigned short for parameter '"+ n+"'");
return value;
}

void
ModCamClay_semiExpl_coupledParametersInitializer::readParameters(ModCamClay_semiExpl_coupledParametersInitializer& pi,const char* const fn){
auto tokenize = [](const std::string& line){
std::istringstream tokenizer(line);
std::vector<std::string> tokens;
std::copy(std::istream_iterator<std::string>(tokenizer),
std::istream_iterator<std::string>(),
std::back_inserter(tokens));
return tokens;
};
std::ifstream f(fn);
if(!f){
return;
}
size_t ln = 1u;
auto line = std::string{};
while(std::getline(f,line)){
auto tokens = tokenize(line);
auto throw_if = [line_number = ln, fn](const bool mfront_c,
const std::string& mfront_error_message){
tfel::raise_if(mfront_c,"ModCamClay_semiExpl_coupledParametersInitializer::readParameters: "
"error at line '"+std::to_string(line_number)+"' "
"while reading parameter file '"+std::string(fn)+"'"
"("+mfront_error_message+")");
};
if(tokens.empty()){
continue;
}
if(tokens[0][0]=='#'){
continue;
}
throw_if(tokens.size()!=2u,"invalid number of tokens");
if("theta"==tokens[0]){
pi.theta = ModCamClay_semiExpl_coupledParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("epsilon"==tokens[0]){
pi.epsilon = ModCamClay_semiExpl_coupledParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("iterMax"==tokens[0]){
pi.iterMax = ModCamClay_semiExpl_coupledParametersInitializer::getUnsignedShort(tokens[0],tokens[1]);
} else if("minimal_time_step_scaling_factor"==tokens[0]){
pi.minimal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("maximal_time_step_scaling_factor"==tokens[0]){
pi.maximal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::getDouble(tokens[0],tokens[1]);
} else if("numerical_jacobian_epsilon"==tokens[0]){
pi.numerical_jacobian_epsilon = ModCamClay_semiExpl_coupledParametersInitializer::getDouble(tokens[0],tokens[1]);
} else {
throw_if(true,"invalid parameter '"+tokens[0]+"'");
}
}
}

} // end of namespace tfel::material

