/*!
* \file   TFEL/Material/ModCamClay_semiExpl_coupledIntegrationData.hxx
* \brief  this file implements the ModCamClay_semiExpl_coupledIntegrationData class.
*         File generated by tfel version 4.2.4-dev
* \author Aqeel Afzal Chaudhry , Christian Silbermann , Eric Simo , Miguel Mánica , Thomas Helfer , Thomas Nagel
* \date   01 / 09 / 2025
 */

#ifndef LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_INTEGRATION_DATA_HXX
#define LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_INTEGRATION_DATA_HXX

#include<string>
#include<iostream>
#include<limits>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsScalar.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/TypeTraits/Promote.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Math/stensor.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include "MFront/GenericBehaviour/State.hxx"
#include "MFront/GenericBehaviour/BehaviourData.hxx"
namespace tfel::material{

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType, bool use_qt>
class ModCamClay_semiExpl_coupledIntegrationData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
 operator <<(std::ostream&,const ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>&);

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>
{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const ModCamClay_semiExpl_coupledIntegrationData&);

static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = tfel::math::tvector<(StensorSize)*(StensorSize)+(StensorSize)*(1)+(StensorSize)*(1)+(1)*(1),real>;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected: 

/*!
 * \brief tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 increment
 */
StrainStensor dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52;

/*!
 * \brief ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F increment
 */
real dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;

/*!
 * \brief time increment
 */
time dt;

temperature dT;
public:

/*!
* \brief Default constructor
*/
ModCamClay_semiExpl_coupledIntegrationData()
{}

/*!
* \brief Copy constructor
*/
ModCamClay_semiExpl_coupledIntegrationData(const ModCamClay_semiExpl_coupledIntegrationData& src)
: dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52(src.dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52),
dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(src.dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F),
dt(src.dt),
dT(src.dT)
{}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
ModCamClay_semiExpl_coupledIntegrationData(const mfront::gb::BehaviourData& mgb_d)
: dt(mgb_d.dt),
dT(mgb_d.s1.external_state_variables[0]-mgb_d.s0.external_state_variables[0])
{
}


/*
* \brief scale the integration data by a scalar.
*/
template<typename Scal>
TFEL_HOST_DEVICE typename std::enable_if<
tfel::typetraits::IsFundamentalNumericType<Scal>::cond&&
tfel::typetraits::IsScalar<Scal>::cond&&
tfel::typetraits::IsReal<Scal>::cond&&
std::is_same<NumericType,typename tfel::typetraits::Promote<NumericType,Scal>::type>::value,
ModCamClay_semiExpl_coupledIntegrationData&
>::type
scale(const ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>&, const Scal time_scaling_factor){
this->dt   *= time_scaling_factor;
this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 *= time_scaling_factor;
this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F *= time_scaling_factor;
this->dT *= time_scaling_factor;
return *this;
}

/*!
* \brief update the driving variable in case of substepping.
*/
TFEL_HOST_DEVICE ModCamClay_semiExpl_coupledIntegrationData&
updateDrivingVariables(const ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>&){
return *this;
}

}; // end of ModCamClay_semiExpl_coupledIntegrationDataclass

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>& b)
{
os << "Δεᵗᵒ : " << b.dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 << '\n';
os << "σ : " << b.tfel_unicode_mangling_03C3 << '\n';
os << "Δpᴸᴿ : " << b.dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F << '\n';
os << "Sᴸ : " << b.Stfel_unicode_mangling_1D38 << '\n';
os << "Δt : " << b.dt << '\n';
os << "ΔT : " << b.dT << '\n';
return os;
}

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_INTEGRATION_DATA_HXX */
