/*!
* \file   TFEL/Material/ModCamClay_semiExpl_coupledBehaviourData.hxx
* \brief  this file implements the ModCamClay_semiExpl_coupledBehaviourData class.
*         File generated by tfel version 4.2.4-dev
* \author Aqeel Afzal Chaudhry , Christian Silbermann , Eric Simo , Miguel Mánica , Thomas Helfer , Thomas Nagel
* \date   01 / 09 / 2025
 */

#ifndef LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_BEHAVIOUR_DATA_HXX
#define LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_BEHAVIOUR_DATA_HXX

#include<limits>
#include<string>
#include<sstream>
#include<iostream>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/Abs.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Math/Array/ViewsArrayIO.hxx"
#include"TFEL/Math/Array/fsarrayIO.hxx"
#include"TFEL/Math/Array/runtime_arrayIO.hxx"
#include"TFEL/Math/fsarray.hxx"
#include"TFEL/Math/runtime_array.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/stensor.hxx"
#include"TFEL/Math/Stensor/StensorConceptIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Math/ST2toST2/ConvertToTangentModuli.hxx"
#include"TFEL/Math/ST2toST2/ConvertSpatialModuliToKirchhoffJaumanRateModuli.hxx"
#include"TFEL/Material/FiniteStrainBehaviourTangentOperator.hxx"
#include"TFEL/Material/ModellingHypothesis.hxx"

#include "MFront/GenericBehaviour/State.hxx"
#include "MFront/GenericBehaviour/BehaviourData.hxx"
namespace tfel::material{

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename,bool>
class ModCamClay_semiExpl_coupledBehaviourData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType,bool use_qt>
class ModCamClay_semiExpl_coupledIntegrationData;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
std::ostream&
 operator <<(std::ostream&,const ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType,false>&);

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType,false>
{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const ModCamClay_semiExpl_coupledBehaviourData&);

/* integration data is declared friend to access   driving variables at the beginning of the time step */
friend class ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>;

static constexpr unsigned short TVectorSize = N;
using StensorDimeToSize = tfel::math::StensorDimeToSize<N>;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
using TensorDimeToSize = tfel::math::TensorDimeToSize<N>;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = tfel::math::tvector<(StensorSize)*(StensorSize)+(StensorSize)*(1)+(StensorSize)*(1)+(1)*(1),real>;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

protected:

StrainStensor tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52;

StressStensor tfel_unicode_mangling_03C3;

real ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;

real Stfel_unicode_mangling_1D38;

#line 57 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03BD;
#line 60 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real M;
#line 63 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real ka;
#line 66 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real la;
#line 69 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
stress pc_char;
#line 72 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070;
#line 75 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03B1;
#line 77 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47;
#line 79 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3;
#line 81 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3;
#line 83 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real ptfel_unicode_mangling_1D47;
#line 85 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33;
#line 88 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real bishop_type;
#line 91 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real bishop_value;
#line 95 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
#line 97 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
#line 99 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097;
#line 101 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095;

#line 36 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
StressStensor tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
#line 39 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
StrainStensor tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
#line 42 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_039Btfel_unicode_mangling_209A;
#line 47 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
stress pc;
#line 50 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097;
#line 53 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real vtfel_unicode_mangling_02B3;
temperature T;

public:

/*!
* \brief Default constructor
*/
ModCamClay_semiExpl_coupledBehaviourData()
{}

/*!
* \brief copy constructor
*/
ModCamClay_semiExpl_coupledBehaviourData(const ModCamClay_semiExpl_coupledBehaviourData& src)
: tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52(src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52),
tfel_unicode_mangling_03C3(src.tfel_unicode_mangling_03C3),
ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(src.ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F),
Stfel_unicode_mangling_1D38(src.Stfel_unicode_mangling_1D38),
tfel_unicode_mangling_03BD(src.tfel_unicode_mangling_03BD),
M(src.M),
ka(src.ka),
la(src.la),
pc_char(src.pc_char),
vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070(src.vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070),
tfel_unicode_mangling_03B1(src.tfel_unicode_mangling_03B1),
tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47(src.tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3(src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3),
Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3(src.Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3),
ptfel_unicode_mangling_1D47(src.ptfel_unicode_mangling_1D47),
mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33(src.mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33),
bishop_type(src.bishop_type),
bishop_value(src.bishop_value),
ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(src.ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7),
mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(src.mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097(src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095(src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095),
tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(src.tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7),
tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1),
tfel_unicode_mangling_039Btfel_unicode_mangling_209A(src.tfel_unicode_mangling_039Btfel_unicode_mangling_209A),
pc(src.pc),
tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097(src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097),
vtfel_unicode_mangling_02B3(src.vtfel_unicode_mangling_02B3),
T(src.T)
{}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
ModCamClay_semiExpl_coupledBehaviourData(const mfront::gb::BehaviourData& mgb_d)
: tfel_unicode_mangling_03BD(mgb_d.s1.material_properties[0]),
M(mgb_d.s1.material_properties[1]),
ka(mgb_d.s1.material_properties[2]),
la(mgb_d.s1.material_properties[3]),
pc_char(mgb_d.s1.material_properties[4]),
vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070(mgb_d.s1.material_properties[5]),
tfel_unicode_mangling_03B1(mgb_d.s1.material_properties[6]),
tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47(mgb_d.s1.material_properties[7]),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3(mgb_d.s1.material_properties[8]),
Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3(mgb_d.s1.material_properties[9]),
ptfel_unicode_mangling_1D47(mgb_d.s1.material_properties[10]),
mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33(mgb_d.s1.material_properties[11]),
bishop_type(mgb_d.s1.material_properties[12]),
bishop_value(mgb_d.s1.material_properties[13]),
ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mgb_d.s1.material_properties[14]),
mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mgb_d.s1.material_properties[15]),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097(mgb_d.s1.material_properties[16]),
Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095(mgb_d.s1.material_properties[17]),
tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(tfel::math::map<StressStensor>(mgb_d.s0.internal_state_variables + 0)),
tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(tfel::math::map<StrainStensor>(mgb_d.s0.internal_state_variables + StensorSize)),
tfel_unicode_mangling_039Btfel_unicode_mangling_209A(mgb_d.s0.internal_state_variables[2*StensorSize]),
pc(mgb_d.s0.internal_state_variables[2*StensorSize+1]),
tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097(mgb_d.s0.internal_state_variables[2*StensorSize+2]),
vtfel_unicode_mangling_02B3(mgb_d.s0.internal_state_variables[2*StensorSize+3]),
T(mgb_d.s0.external_state_variables[0])
{
this-> tfel_unicode_mangling_03C3 = tfel::math::map<StressStensor>(mgb_d.s0.thermodynamic_forces);
this->Stfel_unicode_mangling_1D38 = mgb_d.s0.thermodynamic_forces[StensorSize];
}


/*
* \brief Assignement operator
*/
ModCamClay_semiExpl_coupledBehaviourData&
operator=(const ModCamClay_semiExpl_coupledBehaviourData& src){
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 = src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52;
this->tfel_unicode_mangling_03C3 = src.tfel_unicode_mangling_03C3;
this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F = src.ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;
this->Stfel_unicode_mangling_1D38 = src.Stfel_unicode_mangling_1D38;
this->tfel_unicode_mangling_03BD = src.tfel_unicode_mangling_03BD;
this->M = src.M;
this->ka = src.ka;
this->la = src.la;
this->pc_char = src.pc_char;
this->vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070 = src.vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070;
this->tfel_unicode_mangling_03B1 = src.tfel_unicode_mangling_03B1;
this->tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47 = src.tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47;
this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3 = src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3;
this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3 = src.Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3;
this->ptfel_unicode_mangling_1D47 = src.ptfel_unicode_mangling_1D47;
this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33 = src.mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33;
this->bishop_type = src.bishop_type;
this->bishop_value = src.bishop_value;
this->ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = src.ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
this->mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = src.mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097 = src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097;
this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 = src.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095;
this->tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = src.tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
this->tfel_unicode_mangling_039Btfel_unicode_mangling_209A = src.tfel_unicode_mangling_039Btfel_unicode_mangling_209A;
this->pc = src.pc;
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097 = src.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097;
this->vtfel_unicode_mangling_02B3 = src.vtfel_unicode_mangling_02B3;
this->T = src.T;
return *this;
}

TFEL_HOST_DEVICE void exportStateData(mfront::gb::State& mbg_s1) const
{
using namespace tfel::math;
tfel::math::map<StressStensor>(mbg_s1.thermodynamic_forces) = this->tfel_unicode_mangling_03C3;
mbg_s1.thermodynamic_forces[StensorSize] = this->Stfel_unicode_mangling_1D38;
tfel::math::map<StressStensor>(mbg_s1.internal_state_variables) = this->tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
tfel::math::map<StrainStensor>(mbg_s1.internal_state_variables + StensorSize) = this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
mbg_s1.internal_state_variables[2*StensorSize] = this->tfel_unicode_mangling_039Btfel_unicode_mangling_209A;
mbg_s1.internal_state_variables[2*StensorSize+1] = this->pc;
mbg_s1.internal_state_variables[2*StensorSize+2] = this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097;
mbg_s1.internal_state_variables[2*StensorSize+3] = this->vtfel_unicode_mangling_02B3;
} // end of exportStateData

}; // end of ModCamClay_semiExpl_coupledBehaviourDataclass

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 << '\n';
os << "σ : " << b.tfel_unicode_mangling_03C3 << '\n';
os << "pᴸᴿ : " << b.ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F << '\n';
os << "Sᴸ : " << b.Stfel_unicode_mangling_1D38 << '\n';
os << "ν : " << b.tfel_unicode_mangling_03BD << '\n';
os << "M : " << b.M << '\n';
os << "ka : " << b.ka << '\n';
os << "la : " << b.la << '\n';
os << "pc_char : " << b.pc_char << '\n';
os << "vʳ⁰ : " << b.vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070 << '\n';
os << "α : " << b.tfel_unicode_mangling_03B1 << '\n';
os << "αᵇ : " << b.tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47 << '\n';
os << "Sᴸʳ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3 << '\n';
os << "Sᴳʳ : " << b.Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3 << '\n';
os << "pᵇ : " << b.ptfel_unicode_mangling_1D47 << '\n';
os << "mⱽᴳ : " << b.mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33 << '\n';
os << "bishop_type : " << b.bishop_type << '\n';
os << "bishop_value : " << b.bishop_value << '\n';
os << "pˢʷ : " << b.ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "mˢʷ : " << b.mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "Sᴸₗ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097 << '\n';
os << "Sᴸₕ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 << '\n';
os << "σˢʷ : " << b.tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "εᵉˡ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 << '\n';
os << "Λₚ : " << b.tfel_unicode_mangling_039Btfel_unicode_mangling_209A << '\n';
os << "pc : " << b.pc << '\n';
os << "εᵛₚₗ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097 << '\n';
os << "vʳ : " << b.vtfel_unicode_mangling_02B3 << '\n';
os << "T : " << b.T << '\n';
return os;
}

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_BEHAVIOUR_DATA_HXX */
