/*!
* \file   TFEL/Material/ModCamClay_semiExpl_coupled.hxx
* \brief  this file implements the ModCamClay_semiExpl_coupled Behaviour.
*         File generated by tfel version 4.2.4-dev
* \author Aqeel Afzal Chaudhry , Christian Silbermann , Eric Simo , Miguel Mánica , Thomas Helfer , Thomas Nagel
* \date   01 / 09 / 2025
 */

#ifndef LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_HXX
#define LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_HXX

#include<string>
#include<iostream>
#include<limits>
#include<stdexcept>
#include<algorithm>

#include"TFEL/Raise.hxx"
#include"TFEL/PhysicalConstants.hxx"
#include"TFEL/Config/TFELConfig.hxx"
#include"TFEL/Config/TFELTypes.hxx"
#include"TFEL/TypeTraits/IsFundamentalNumericType.hxx"
#include"TFEL/TypeTraits/IsReal.hxx"
#include"TFEL/Math/General/IEEE754.hxx"
#include"TFEL/Material/MaterialException.hxx"
#include"TFEL/Material/MechanicalBehaviour.hxx"
#include"TFEL/Material/MechanicalBehaviourTraits.hxx"
#include"TFEL/Material/OutOfBoundsPolicy.hxx"
#include"TFEL/Material/BoundsCheck.hxx"
#include"TFEL/Material/IsotropicPlasticity.hxx"
#include"TFEL/Material/Lame.hxx"
#include"TFEL/Material/Hosford1972YieldCriterion.hxx"
#include"TFEL/Material/ModCamClay_semiExpl_coupledBehaviourData.hxx"
#include"TFEL/Material/ModCamClay_semiExpl_coupledIntegrationData.hxx"

#include"TFEL/Math/Array/ViewsArray.hxx"
#include"TFEL/Math/tvector.hxx"
#include"TFEL/Math/Vector/tvectorIO.hxx"
#include"TFEL/Math/tmatrix.hxx"
#include"TFEL/Math/Matrix/tmatrixIO.hxx"
#include"TFEL/Math/st2tost2.hxx"
#include"TFEL/Math/ST2toST2/ST2toST2ConceptIO.hxx"
#include"TFEL/Math/TinyNewtonRaphsonSolver.hxx"
#include "MFront/GenericBehaviour/State.hxx"
#include "MFront/GenericBehaviour/BehaviourData.hxx"
namespace tfel::material{

struct ModCamClay_semiExpl_coupledParametersInitializer
{
static ModCamClay_semiExpl_coupledParametersInitializer&
get();

double theta;
double epsilon;
unsigned short iterMax;
double minimal_time_step_scaling_factor;
double maximal_time_step_scaling_factor;
double numerical_jacobian_epsilon;

void set(const char* const,const double);

void set(const char* const,const unsigned short);

/*!
 * \brief convert a string to double
 * \param[in] p : parameter
 * \param[in] v : value
 */
static double getDouble(const std::string&,const std::string&);
/*!
 * \brief convert a string to unsigned short
 * \param[in] p : parameter
 * \param[in] v : value
 */
static unsigned short getUnsignedShort(const std::string&,const std::string&);
private :

ModCamClay_semiExpl_coupledParametersInitializer();

ModCamClay_semiExpl_coupledParametersInitializer(const ModCamClay_semiExpl_coupledParametersInitializer&);

ModCamClay_semiExpl_coupledParametersInitializer&
operator=(const ModCamClay_semiExpl_coupledParametersInitializer&);
/*!
 * \brief read the parameters from the given file
 * \param[out] pi : parameters initializer
 * \param[in]  fn : file name
 */
static void readParameters(ModCamClay_semiExpl_coupledParametersInitializer&,const char* const);
};

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis, typename NumericType, bool use_qt>
struct ModCamClay_semiExpl_coupled;

//! \brief forward declaration
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
 operator <<(std::ostream&,const ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>&);

/*!
* \class ModCamClay_semiExpl_coupled
* \brief This class implements the ModCamClay_semiExpl_coupled behaviour.
* \tparam hypothesis: modelling hypothesis.
* \tparam NumericType: numerical type.
* \author Aqeel Afzal Chaudhry , Christian Silbermann , Eric Simo , Miguel Mánica , Thomas Helfer , Thomas Nagel
* \date   01 / 09 / 2025
* The modified cam - clay model according to Callari ( 1998 ) : 
* A finite-strain cam-clay model in the framework of multiplicative elasto-plasticity 
* but here in a consistent geometrically linear form ( linearized volume ratio evolution ) 
* semi - explicit due to explicit volume ratio update at the end of time step , 
* nonlinear hypoelastic behavior : pressure - dependent bulk modulus , constant Poisson ratio , 
* incremental formulation assuming constant elastic parameters over the time step , 
* normalized plastic flow direction , lower limit for a minimal pre - consolidation pressure , 
* with hydraulic and thermal coupling , saturation dependent swelling , 
*/
template<ModellingHypothesis::Hypothesis hypothesis,typename NumericType>
struct ModCamClay_semiExpl_coupled<hypothesis, NumericType, false> final
: public MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>,
public ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>,
public ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>,
public tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>>{

static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;

static_assert(N==1||N==2||N==3);
static_assert(tfel::typetraits::IsFundamentalNumericType<NumericType>::cond);
static_assert(tfel::typetraits::IsReal<NumericType>::cond);

friend std::ostream& operator<< <>(std::ostream&,const ModCamClay_semiExpl_coupled&);

friend struct tfel::math::TinyNonLinearSolverBase<2*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, ModCamClay_semiExpl_coupled>;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;

using ushort =  unsigned short;
using Types = tfel::config::Types<N, NumericType, false>;
using Type = NumericType;
using numeric_type = typename Types::numeric_type;
using real = typename Types::real;
using time = typename Types::time;
using length = typename Types::length;
using frequency = typename Types::frequency;
using speed = typename Types::speed;
using stress = typename Types::stress;
using strain = typename Types::strain;
using strainrate = typename Types::strainrate;
using stressrate = typename Types::stressrate;
using temperature = typename Types::temperature;
using thermalexpansion = typename Types::thermalexpansion;
using thermalconductivity = typename Types::thermalconductivity;
using massdensity = typename Types::massdensity;
using energydensity = typename Types::energydensity;
using TVector = typename Types::TVector;
using DisplacementTVector = typename Types::DisplacementTVector;
using ForceTVector = typename Types::ForceTVector;
using HeatFlux = typename Types::HeatFlux;
using TemperatureGradient = typename Types::TemperatureGradient;
using Stensor = typename Types::Stensor;
using StressStensor = typename Types::StressStensor;
using StressRateStensor = typename Types::StressRateStensor;
using StrainStensor = typename Types::StrainStensor;
using StrainRateStensor = typename Types::StrainRateStensor;
using FrequencyStensor = typename Types::FrequencyStensor;
using Tensor = typename Types::Tensor;
using DeformationGradientTensor = typename Types::DeformationGradientTensor;
using DeformationGradientRateTensor = typename Types::DeformationGradientRateTensor;
using StressTensor = typename Types::StressTensor;
using StiffnessTensor = typename Types::StiffnessTensor;
using Stensor4 = typename Types::Stensor4;
using TangentOperator = tfel::math::tvector<(StensorSize)*(StensorSize)+(StensorSize)*(1)+(StensorSize)*(1)+(1)*(1),real>;
using PhysicalConstants = tfel::PhysicalConstants<NumericType, false>;

public :

typedef ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false> BehaviourData;
typedef ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false> IntegrationData;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::SMFlag SMFlag;
typedef typename MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::SMType SMType;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::ELASTIC;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::SECANTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::TANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::CONSISTENTTANGENTOPERATOR;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::NOSTIFFNESSREQUESTED;
using IntegrationResult = typename MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::IntegrationResult;

using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
using MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::UNRELIABLE_RESULTS;

private :


#line 45 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
strain rpc;

#line 36 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
tfel::math::View<StressStensor> dtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
#line 39 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
tfel::math::View<StrainStensor> dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
#line 42 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real& dtfel_unicode_mangling_039Btfel_unicode_mangling_209A;
#line 45 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real& drpc;

#line 105 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real K;
#line 106 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03C6;
#line 107 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03C6tfel_unicode_mangling_2080;
#line 108 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_2202tfel_unicode_mangling_03C6tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38;
#line 109 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
#line 110 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03C7;
#line 111 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_03C7tfel_unicode_mangling_2080;
#line 112 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38;
#line 113 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
StressStensor tfel_unicode_mangling_03C3tfel_unicode_mangling_2080;
#line 114 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
StiffnessTensor tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
#line 115 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
bool withinElasticRange;
#line 116 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real Mtfel_unicode_mangling_00B2;
#line 117 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real young;
#line 118 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real pc_min;
#line 119 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
real rpc_min;

NumericType theta;
NumericType epsilon;
ushort iterMax;
real minimal_time_step_scaling_factor;
real maximal_time_step_scaling_factor;
NumericType numerical_jacobian_epsilon;

//! Tangent operator;
TangentOperator Dt;
tfel::math::View<tfel::math::derivative_type<StressStensor,StrainStensor>> dtfel_unicode_mangling_03C3_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52;
tfel::math::View<tfel::math::derivative_type<StressStensor,temperature>> dtfel_unicode_mangling_03C3_ddT;
tfel::math::View<tfel::math::derivative_type<StressStensor,real>> dtfel_unicode_mangling_03C3_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;
tfel::math::derivative_type<real,real>& dStfel_unicode_mangling_1D38_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;
// updating material properties, in mandatory
TFEL_HOST_DEVICE void updateMaterialPropertiesDependantOnStateVariables(){
using namespace std;
using namespace tfel::math;
using std::vector;
}

SMType stiffness_matrix_type;
TFEL_HOST_DEVICE void computeNumericalJacobian(tfel::math::tmatrix<2*StensorSize+2,2*StensorSize+2, NumericType>& njacobian)
{
using namespace std;
using namespace tfel::math;
tvector<2*StensorSize+2, NumericType> tzeros(this->zeros);
tvector<2*StensorSize+2, NumericType> tfzeros(this->fzeros);
tmatrix<2*StensorSize+2,2*StensorSize+2, NumericType> tjacobian(this->jacobian);
for(ushort mfront_idx = 0; mfront_idx != 2*StensorSize+2; ++mfront_idx){
this->zeros(mfront_idx) -= this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->zeros = tzeros;
tvector<2*StensorSize+2, NumericType> tfzeros2(this->fzeros);
this->zeros(mfront_idx) += this->numerical_jacobian_epsilon;
this->computeThermodynamicForces();
this->computeFdF(true);
this->fzeros = (this->fzeros-tfzeros2) / (2 * (this->numerical_jacobian_epsilon));
for(ushort mfront_idx2 = 0; mfront_idx2!= 2*StensorSize+2; ++mfront_idx2){
njacobian(mfront_idx2,mfront_idx) = this->fzeros(mfront_idx2);
}
this->zeros    = tzeros;
this->fzeros   = tfzeros;
}
if(&njacobian!=&(this->jacobian)){
this->jacobian = tjacobian;
}
}

[[nodiscard]] TFEL_HOST_DEVICE bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

[[nodiscard]] TFEL_HOST_DEVICE bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
for(ushort mfront_idx2=StensorSize; mfront_idx2!=2*StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
}
return true;
}

[[nodiscard]] TFEL_HOST_DEVICE bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
for(ushort mfront_idx2=StensorSize; mfront_idx2!=2*StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A(mfront_idx)=vect_e(2*StensorSize);
}
return true;
}

[[nodiscard]] TFEL_HOST_DEVICE bool
computePartialJacobianInvert(const tfel::math::TinyPermutation<2*StensorSize+2>& jacobian_permutation, tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_rpc)
{
using namespace tfel::math;
for(ushort mfront_idx=0; mfront_idx !=StensorSize; ++mfront_idx){
tvector<2*StensorSize+2, NumericType> vect_e(NumericType(0));
vect_e(mfront_idx) = NumericType(1);
if(!TinyMatrixSolve<2*StensorSize+2, NumericType, false>::back_substitute(this->jacobian, jacobian_permutation, vect_e)){
return false;
}
for(ushort mfront_idx2=0; mfront_idx2!=StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
for(ushort mfront_idx2=StensorSize; mfront_idx2!=2*StensorSize; ++mfront_idx2){
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(mfront_idx2,mfront_idx)=vect_e(mfront_idx2);
}
partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A(mfront_idx)=vect_e(2*StensorSize);
partial_jacobian_rpc(mfront_idx)=vect_e(2*StensorSize+1);
}
return true;
}

TFEL_HOST_DEVICE void additionalConvergenceChecks(bool& converged, const NumericType& error){
using namespace std;
using namespace tfel::math;
using std::vector;
const auto smt = this->stiffness_matrix_type;
#line 299 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (converged)
#line 300 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 301 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (!this->withinElasticRange)
#line 302 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 303 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A < 0)
#line 304 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 305 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
converged = false;
#line 306 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->withinElasticRange = true;
#line 307 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 308 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 309 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
static_cast<void>(converged);
static_cast<void>(error);
static_cast<void>(smt);
} // end of additionalConvergenceChecks

TFEL_HOST_DEVICE void computeThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
#line 222 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C3 = this->tfel_unicode_mangling_03C3tfel_unicode_mangling_2080 + theta * this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 * this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 - 3 * this->K * this->tfel_unicode_mangling_03B1 * this->dT * Stensor::Id() - this->tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 * Stensor::Id();
} // end of ModCamClay_semiExpl_coupled::computeThermodynamicForces

TFEL_HOST_DEVICE void computeFinalThermodynamicForces(){
using namespace std;
using namespace tfel::math;
using std::vector;
#line 285 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C3 = this->tfel_unicode_mangling_03C3tfel_unicode_mangling_2080 + this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 * this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 - 3 * this->K * this->tfel_unicode_mangling_03B1 * this->dT * Stensor::Id() - this->tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47 * this->tfel_unicode_mangling_03C7 * (this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F+this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) * Stensor::Id() - this->tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 * Stensor::Id();
} // end of ModCamClay_semiExpl_coupled::computeFinalThermodynamicForces

/*!
* \brief Update internal variables at end of integration
*/
TFEL_HOST_DEVICE void updateIntegrationVariables(){
this->rpc += this->drpc;
}

/*!
* \brief Update internal variables at end of integration
*/
TFEL_HOST_DEVICE void updateStateVariables(){
this->tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 += this->dtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7;
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 += this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
this->tfel_unicode_mangling_039Btfel_unicode_mangling_209A += this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A;
}

/*!
* \brief Update auxiliary state variables at end of integration
*/
TFEL_HOST_DEVICE void updateAuxiliaryStateVariables(){
using namespace std;
using namespace tfel::math;
#line 291 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 -= this->tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 * Stensor::Id();
#line 292 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->pc += this->drpc * this->young;
#line 293 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097 += trace(this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 - this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 - this->tfel_unicode_mangling_03B1 * this->dT * Stensor::Id());
#line 294 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->vtfel_unicode_mangling_02B3 += this->vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070 * trace(this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 - this->tfel_unicode_mangling_03B1 * this->dT * Stensor::Id());
}

//! \brief Default constructor (disabled)
ModCamClay_semiExpl_coupled() =delete ;
//! \brief Copy constructor (disabled)
ModCamClay_semiExpl_coupled(const ModCamClay_semiExpl_coupled&) = delete;
//! \brief Assignement operator (disabled)
ModCamClay_semiExpl_coupled& operator = (const ModCamClay_semiExpl_coupled&) = delete;

public:

/*!
* \brief Constructor
*/
ModCamClay_semiExpl_coupled(const ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>& src1,
const ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>& src2)
: ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>(src1),
ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>(src2),
dtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(tfel::math::map<StressStensor, 0>(this->zeros)),
dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(tfel::math::map<StrainStensor, StensorSize>(this->zeros)),
dtfel_unicode_mangling_039Btfel_unicode_mangling_209A(this->zeros(2*StensorSize)),
drpc(this->zeros(2*StensorSize+1)),
dtfel_unicode_mangling_03C3_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52(Dt.begin()),
dtfel_unicode_mangling_03C3_ddT(Dt.begin()+StensorSize*StensorSize),
dtfel_unicode_mangling_03C3_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(Dt.begin()+StensorSize*StensorSize+StensorSize),
dStfel_unicode_mangling_1D38_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(Dt[StensorSize*StensorSize+2*StensorSize])
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->theta = ModCamClay_semiExpl_coupledParametersInitializer::get().theta;
this->epsilon = ModCamClay_semiExpl_coupledParametersInitializer::get().epsilon;
this->iterMax = ModCamClay_semiExpl_coupledParametersInitializer::get().iterMax;
this->minimal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::get().maximal_time_step_scaling_factor;
this->numerical_jacobian_epsilon = ModCamClay_semiExpl_coupledParametersInitializer::get().numerical_jacobian_epsilon;
}

/*
 * \brief constructor for the Generic interface
 * \param[in] mgb_d: behaviour data
 */
ModCamClay_semiExpl_coupled(const mfront::gb::BehaviourData& mgb_d)
: ModCamClay_semiExpl_coupledBehaviourData<hypothesis, NumericType, false>(mgb_d),
ModCamClay_semiExpl_coupledIntegrationData<hypothesis, NumericType, false>(mgb_d),
dtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7(tfel::math::map<StressStensor, 0>(this->zeros)),
dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1(tfel::math::map<StrainStensor, StensorSize>(this->zeros)),
dtfel_unicode_mangling_039Btfel_unicode_mangling_209A(this->zeros(2*StensorSize)),
drpc(this->zeros(2*StensorSize+1)),
dtfel_unicode_mangling_03C3_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52(Dt.begin()),
dtfel_unicode_mangling_03C3_ddT(Dt.begin()+StensorSize*StensorSize),
dtfel_unicode_mangling_03C3_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(Dt.begin()+StensorSize*StensorSize+StensorSize),
dStfel_unicode_mangling_1D38_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F(Dt[StensorSize*StensorSize+2*StensorSize])
{
using namespace std;
using namespace tfel::math;
using std::vector;
this->theta = ModCamClay_semiExpl_coupledParametersInitializer::get().theta;
this->epsilon = ModCamClay_semiExpl_coupledParametersInitializer::get().epsilon;
this->iterMax = ModCamClay_semiExpl_coupledParametersInitializer::get().iterMax;
this->minimal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::get().minimal_time_step_scaling_factor;
this->maximal_time_step_scaling_factor = ModCamClay_semiExpl_coupledParametersInitializer::get().maximal_time_step_scaling_factor;
this->numerical_jacobian_epsilon = ModCamClay_semiExpl_coupledParametersInitializer::get().numerical_jacobian_epsilon;
this-> tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 = tfel::math::map<StrainStensor>(mgb_d.s0.gradients);
tfel::fsalgo::transform<StensorSize>::exe(mgb_d.s1.gradients,mgb_d.s0.gradients,this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52.begin(),std::minus<real>());
this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F = mgb_d.s0.gradients[StensorSize];
this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F = mgb_d.s1.gradients[StensorSize] - mgb_d.s0.gradients[StensorSize];
}

/*!
 * \ brief initialize the behaviour with user code
 */
[[nodiscard]] TFEL_HOST_DEVICE bool initialize(){
using namespace std;
using namespace tfel::math;
using std::vector;
#line 127 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto Stfel_unicode_mangling_2091 = [&](const auto ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56) {
#line 128 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
return std::pow(
#line 129 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
std::pow(std::max(ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56, 0.0) / this->ptfel_unicode_mangling_1D47, 1.0 / (1.0 - this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33)) + 1.0, -this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33);
#line 130 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
};
#line 132 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double Stfel_unicode_mangling_2080 = Stfel_unicode_mangling_2091(-(this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F)) * (1.0 - this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3) + this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3;
#line 133 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080 = std::clamp(Stfel_unicode_mangling_2080, this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3, 1.0 - this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3);
#line 135 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double S = Stfel_unicode_mangling_2091(-(this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F + this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F)) * (1.0 - this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3) + this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3;
#line 136 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->Stfel_unicode_mangling_1D38 = std::clamp(S, this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3, 1.0 - this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3);
#line 139 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const int model_type = static_cast<int>(this->bishop_type);
#line 140 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (model_type == 0) {
#line 141 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7 = std::pow(this->Stfel_unicode_mangling_1D38, this->bishop_value);
#line 142 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = this->bishop_value * std::pow(this->Stfel_unicode_mangling_1D38, this->bishop_value - 1);
#line 143 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7tfel_unicode_mangling_2080 = std::pow(Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080, this->bishop_value);
#line 144 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 145 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else if (model_type == 1) {
#line 146 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double S_cut = this->bishop_value;
#line 147 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (this->Stfel_unicode_mangling_1D38 < S_cut) {
#line 148 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7 = 0.0;
#line 149 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = 0.0;
#line 150 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
} else if (this->Stfel_unicode_mangling_1D38 > 1.0) {
#line 151 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7 = 1.0;
#line 152 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = 0.0;
#line 153 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
} else {
#line 154 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double denom = std::max(1e-15, 1.0 - S_cut);
#line 155 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7 = (this->Stfel_unicode_mangling_1D38 - S_cut) / denom;
#line 156 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = 1.0 / denom;
#line 157 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 158 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C7tfel_unicode_mangling_2080 = (Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080 < S_cut) ? 0.0 :
#line 159 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
(Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080 > 1.0) ? 1.0 :
#line 160 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
(Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080 - S_cut) / std::max(1e-15, 1.0 - S_cut);
#line 161 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 162 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else {
#line 163 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
throw std::runtime_error("Invalid BishopsModelType: must be 0 (power law) or 1 (cutoff).");
#line 164 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 167 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if (this->Stfel_unicode_mangling_1D38 <= this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097)
#line 168 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 169 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C6 = 0.0;
#line 170 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C6tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = 0.0;
#line 171 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 172 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else if (this->Stfel_unicode_mangling_1D38 >= this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095)
#line 173 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 174 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C6 = 1.0;
#line 175 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C6tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = 0.0;
#line 176 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 177 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else
#line 178 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 179 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const double normalized = (this->Stfel_unicode_mangling_1D38 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097) / (this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097);
#line 180 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C6 = std::pow(normalized, this->mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7);
#line 181 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C6tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38 = this->mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 / (this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097) * std::pow(normalized, this->mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 - 1);
#line 182 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 184 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C6tfel_unicode_mangling_2080 = std::pow((Stfel_unicode_mangling_1D38tfel_unicode_mangling_2080 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097) / (this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 - this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097) , this->mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7);
#line 187 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = this->ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 * (this->tfel_unicode_mangling_03C6 - this->tfel_unicode_mangling_03C6tfel_unicode_mangling_2080);
#line 189 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
tfel::raise_if(this->la < this->ka, "Invalid parameters: la<ka");
#line 190 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->Mtfel_unicode_mangling_00B2 = this->M * this->M;
#line 193 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_03C3tfel_unicode_mangling_2080 = this->tfel_unicode_mangling_03C3 + this->tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47 * this->tfel_unicode_mangling_03C7tfel_unicode_mangling_2080 * this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F * Stensor::Id();
#line 196 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->pc_min = 0.5e-8 * this->pc_char;
#line 197 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto p = -trace(this->tfel_unicode_mangling_03C3tfel_unicode_mangling_2080) / 3;
#line 198 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->K = this->vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070 / this->ka * max(p , this->pc_char);
#line 199 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto E = 3.0 * this->K * (1.0 - 2 * this->tfel_unicode_mangling_03BD);
#line 201 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->young = E;
#line 202 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->rpc = this->pc / this->young;
#line 203 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->rpc_min = this->pc_min / this->young;
#line 206 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = E / (1.0 + this->tfel_unicode_mangling_03BD) * Stensor4::K() + this->K * Stensor4::IxI();
#line 209 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_03C3tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = this->tfel_unicode_mangling_03C3tfel_unicode_mangling_2080 + this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 * this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 - 3 * this->K * this->tfel_unicode_mangling_03B1 * this->dT * Stensor::Id() - this->tfel_unicode_mangling_0394ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 * Stensor::Id();
#line 212 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto stfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = deviator(tfel_unicode_mangling_03C3tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1);
#line 213 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto qtfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = sqrt(1.5 * stfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 | stfel_unicode_mangling_1D49tfel_unicode_mangling_02E1);
#line 214 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto ptfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = -trace(tfel_unicode_mangling_03C3tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1) / 3;
#line 216 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto pctfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = this->pc;
#line 217 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto ftfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = qtfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 * qtfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 + this->Mtfel_unicode_mangling_00B2 * ptfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 * (ptfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 - pctfel_unicode_mangling_1D49tfel_unicode_mangling_02E1);
#line 218 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
this->withinElasticRange = ftfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 < 0;
return true;
}

/*!
 * \brief set the policy for "out of bounds" conditions
 */
TFEL_HOST_DEVICE void
setOutOfBoundsPolicy(const OutOfBoundsPolicy policy_value){
  this->policy = policy_value;
} // end of setOutOfBoundsPolicy

/*!
* \return the modelling hypothesis
*/
constexpr ModellingHypothesis::Hypothesis
getModellingHypothesis() const{
return hypothesis;
} // end of getModellingHypothesis

//! \brief check physical bounds and standard bounds
TFEL_HOST_DEVICE void checkBounds() const{
} // end of checkBounds

[[nodiscard]] IntegrationResult computePredictionOperator(const SMFlag,const SMType) override{
tfel::raise("ModCamClay_semiExpl_coupled::computePredictionOperator: "
"unsupported prediction operator flag");
}

TFEL_HOST_DEVICE real getMinimalTimeStepScalingFactor() const noexcept override{
  return this->minimal_time_step_scaling_factor;
}

TFEL_HOST_DEVICE std::pair<bool, real>
computeAPrioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPrioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                  current_time_step_scaling_factor)};
}

/*!
 * \brief Integrate behaviour law over the time step
 */
[[nodiscard]] TFEL_HOST_DEVICE IntegrationResult integrate(const SMFlag smflag,const SMType smt) override{
using namespace std;
using namespace tfel::math;
this->stiffness_matrix_type = smt;
tfel::raise_if(smflag!=MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::STANDARDTANGENTOPERATOR,
"invalid tangent operator flag");
tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>>::epsilon = this->epsilon;
tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>>::iterMax = this->iterMax;
if(!this->solveNonLinearSystem()){
return MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
if (this->stiffness_matrix_type != NOSTIFFNESSREQUESTED){
this->updateOrCheckJacobian();
}
this->updateIntegrationVariables();
this->updateStateVariables();
this->computeFinalThermodynamicForces();
this->updateAuxiliaryStateVariables();
if(smt!=NOSTIFFNESSREQUESTED){
if(!this->computeConsistentTangentOperator(smt)){
return MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::FAILURE;
}
}
return MechanicalBehaviour<MechanicalBehaviourBase::GENERALBEHAVIOUR,hypothesis, NumericType, false>::SUCCESS;
} // end of ModCamClay_semiExpl_coupled::integrate

TFEL_HOST_DEVICE bool computeResidual(){
this->computeThermodynamicForces();
return this->computeFdF(false);
}
//! \return the norm of the residual
TFEL_HOST_DEVICE NumericType computeResidualNorm() {
return tfel::math::norm(this->fzeros) / (2*StensorSize+2);
}
/*!
 * \brief check the convergence of the method
 * \param[in] error: current error
 */
TFEL_HOST_DEVICE bool checkConvergence(const NumericType error) {
auto converged = error < this->epsilon;
auto mfront_internals_converged = converged;
this->additionalConvergenceChecks(converged, error);
if((mfront_internals_converged) && (!converged)){
this->is_delta_zeros_defined = false;
}
return converged;
}
/*!
 * \brief update the jacobian matrix if required.
 * \param[in] converged: boolean stating if the method is
 * called after the convergence of the algorithm or before
 * the computation of the next correction.
 *
 * This method can be used to compute the jacobian or part
 * of the jacobian numerically. If the jacobian was computed
 * in `computeResidual`, this method can be used to compare it
 * to a numerical approximation.
 */
TFEL_HOST_DEVICE void updateOrCheckJacobian(){
}
/*!
 * \brief method meant to set bounds on some components
 * of the current Newton correction or to implement a line
 * search.
 */
TFEL_HOST_DEVICE void processNewCorrection()
{
}
/*!
 * \brief method meant to process the new estimate.
 *
 * This method may be called to apply bounds on the
 * new estimate and update material properties
 * dependending on the current state.
 */
TFEL_HOST_DEVICE void processNewEstimate(){
this->updateMaterialPropertiesDependantOnStateVariables();
}
/*!
 * \brief solve linear system
 * \return true on success
 * \param[in] m: matrix
 * \param[in,out] v: right hand side on input, solution on output
 */
TFEL_HOST_DEVICE bool solveLinearSystem(tfel::math::tmatrix<2*StensorSize+2, 2*StensorSize+2, NumericType>& mfront_matrix,tfel::math::tvector<2*StensorSize+2, NumericType>& mfront_vector)const noexcept{
auto mfront_success = true;
mfront_success = tfel::math::TinyNewtonRaphsonSolver<2*ModellingHypothesisToStensorSize<hypothesis>::value+2, NumericType, ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>>::solveLinearSystem(mfront_matrix, mfront_vector);
return mfront_success;
}
/*!
* \brief compute fzeros and jacobian
*/
TFEL_HOST_DEVICE bool computeFdF(const bool perturbatedSystemEvaluation){
using namespace std;
using namespace tfel::math;
using std::vector;
// silent compiler warning
static_cast<void>(perturbatedSystemEvaluation); 
constexpr auto tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_offset = 0;
constexpr auto tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_offset = StensorSize;
constexpr auto tfel_unicode_mangling_039Btfel_unicode_mangling_209A_offset = 2*StensorSize;
constexpr auto rpc_offset = 2*StensorSize+1;
auto ftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = tfel::math::map<StressStensor, 0>(this->fzeros);
auto ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel::math::map<StrainStensor, StensorSize>(this->fzeros);
real& ftfel_unicode_mangling_039Btfel_unicode_mangling_209A(this->fzeros(2*StensorSize));
real& frpc(this->fzeros(2*StensorSize+1));
// derivative of residual ftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 with respect to variable tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7
auto&& dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = tfel::math::map_derivative<0, 0, StressStensor, StressStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 with respect to variable tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1
auto&& dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel::math::map_derivative<0, StensorSize, StressStensor, StrainStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 with respect to variable tfel_unicode_mangling_039Btfel_unicode_mangling_209A
auto&& dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = tfel::math::map_derivative<0, 2*StensorSize, StressStensor, real>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 with respect to variable rpc
auto&& dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddrpc = tfel::math::map_derivative<0, 2*StensorSize+1, StressStensor, strain>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 with respect to variable tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7
auto&& dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = tfel::math::map_derivative<StensorSize, 0, StrainStensor, StressStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 with respect to variable tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1
auto&& dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel::math::map_derivative<StensorSize, StensorSize, StrainStensor, StrainStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 with respect to variable tfel_unicode_mangling_039Btfel_unicode_mangling_209A
auto&& dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = tfel::math::map_derivative<StensorSize, 2*StensorSize, StrainStensor, real>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 with respect to variable rpc
auto&& dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddrpc = tfel::math::map_derivative<StensorSize, 2*StensorSize+1, StrainStensor, strain>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_039Btfel_unicode_mangling_209A with respect to variable tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7
auto&& dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = tfel::math::map_derivative<2*StensorSize, 0, real, StressStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_039Btfel_unicode_mangling_209A with respect to variable tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1
auto&& dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel::math::map_derivative<2*StensorSize, StensorSize, real, StrainStensor>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_039Btfel_unicode_mangling_209A with respect to variable tfel_unicode_mangling_039Btfel_unicode_mangling_209A
auto&& dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = tfel::math::map_derivative<2*StensorSize, 2*StensorSize, real, real>(this->jacobian);
// derivative of residual ftfel_unicode_mangling_039Btfel_unicode_mangling_209A with respect to variable rpc
auto&& dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddrpc = tfel::math::map_derivative<2*StensorSize, 2*StensorSize+1, real, strain>(this->jacobian);
// derivative of residual frpc with respect to variable tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7
auto&& dfrpc_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 = tfel::math::map_derivative<2*StensorSize+1, 0, strain, StressStensor>(this->jacobian);
// derivative of residual frpc with respect to variable tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1
auto&& dfrpc_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel::math::map_derivative<2*StensorSize+1, StensorSize, strain, StrainStensor>(this->jacobian);
// derivative of residual frpc with respect to variable tfel_unicode_mangling_039Btfel_unicode_mangling_209A
auto&& dfrpc_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = tfel::math::map_derivative<2*StensorSize+1, 2*StensorSize, strain, real>(this->jacobian);
// derivative of residual frpc with respect to variable rpc
auto&& dfrpc_ddrpc = tfel::math::map_derivative<2*StensorSize+1, 2*StensorSize+1, strain, strain>(this->jacobian);
// setting jacobian to identity
std::fill(this->jacobian.begin(),this->jacobian.end(), NumericType(0));
for(ushort mfront_idx = 0; mfront_idx != 2*StensorSize+2; ++mfront_idx){
this->jacobian(mfront_idx, mfront_idx) = NumericType(1);
}
// setting f values to zeros
this->fzeros = this->zeros;
#line 227 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
constexpr const auto Pr4 = Stensor4::K();
#line 228 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto the = (this->vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070) / ((this->la) - (this->ka));
#line 230 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if ((this->withinElasticRange))
#line 231 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 232 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 -= (this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52);
#line 234 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
return true;
#line 235 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 237 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto epsr = strain(1.e-12);
#line 239 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto s = deviator((this->tfel_unicode_mangling_03C3));
#line 240 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto q = sqrt(1.5 * s | s);
#line 241 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto p = -trace((this->tfel_unicode_mangling_03C3)) / 3;
#line 243 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto rpc_new = (this->rpc) + theta * (this->drpc);
#line 244 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto pc_new = rpc_new * (this->young);
#line 246 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto f = q * q + (this->Mtfel_unicode_mangling_00B2) * p * (p - pc_new);
#line 247 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p = (this->Mtfel_unicode_mangling_00B2) * (2 * p - pc_new);
#line 248 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03C3 = eval(3 * s - tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p * Stensor::Id() / 3);
#line 249 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
auto norm = sqrt(6 * q * q + tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p * tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p / 3);
#line 250 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
norm = max(norm, epsr * (this->young));
#line 251 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto n = tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03C3 / norm;
#line 252 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto ntr = -tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p / norm;
#line 254 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1 = eval((this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A) * n);
#line 255 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B = trace(tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1);
#line 257 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto fchar = (this->pc_char) * (this->young);
#line 260 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
ftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = (this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1) + tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1 - (this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52);
#line 261 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
ftfel_unicode_mangling_039Btfel_unicode_mangling_209A = f / fchar;
#line 262 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
frpc = (this->drpc) + tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B * the * (rpc_new - (this->rpc_min));
#line 265 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202normtfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03C3 = (9 * s - 2 * (this->Mtfel_unicode_mangling_00B2) / 9 * tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p * Stensor::Id()) / norm;
#line 266 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = (3 * Pr4 + 2 * (this->Mtfel_unicode_mangling_00B2) / 9 * (Stensor::Id() ^ Stensor::Id()) - (n ^ tfel_unicode_mangling_2202normtfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03C3)) / norm * (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1) * theta;
#line 267 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394rpc = (Stensor::Id() + tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202p * n / norm) * (this->Mtfel_unicode_mangling_00B2) / (3 * norm) * theta * (this->young);
#line 268 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202frpctfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B = the * (rpc_new - (this->rpc_min));
#line 271 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 += (this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A) * tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1;
#line 272 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = n;
#line 273 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddrpc = (this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A) * tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394rpc;
#line 275 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = (tfel_unicode_mangling_2202ftfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03C3 | (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1)) * theta / fchar;
#line 276 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A  = strain(0);
#line 277 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddrpc = -(this->Mtfel_unicode_mangling_00B2) * p * theta / fchar * (this->young);
#line 279 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dfrpc_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A = tfel_unicode_mangling_2202frpctfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B * ntr;
#line 280 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dfrpc_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 = tfel_unicode_mangling_2202frpctfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B * (this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A) * (Stensor::Id() | tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1);
#line 281 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dfrpc_ddrpc = 1 + tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B * the * theta + tfel_unicode_mangling_2202frpctfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394tfel_unicode_mangling_03B5tfel_unicode_mangling_1D56tfel_unicode_mangling_02E1tfel_unicode_mangling_1D5B * (this->dtfel_unicode_mangling_039Btfel_unicode_mangling_209A) * trace(tfel_unicode_mangling_2202ntfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_0394rpc);
static_cast<void>(dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_ddrpc); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_ddrpc); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A); /* suppress potential warnings */
static_cast<void>(dftfel_unicode_mangling_039Btfel_unicode_mangling_209A_ddrpc); /* suppress potential warnings */
static_cast<void>(dfrpc_ddtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7); /* suppress potential warnings */
static_cast<void>(dfrpc_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1); /* suppress potential warnings */
static_cast<void>(dfrpc_ddtfel_unicode_mangling_039Btfel_unicode_mangling_209A); /* suppress potential warnings */
static_cast<void>(dfrpc_ddrpc); /* suppress potential warnings */
static_cast<void>(tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7_offset);
static_cast<void>(tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1_offset);
static_cast<void>(tfel_unicode_mangling_039Btfel_unicode_mangling_209A_offset);
static_cast<void>(rpc_offset);
return true;
}

TFEL_HOST_DEVICE std::pair<bool, real>
computeAPosterioriTimeStepScalingFactor(const real current_time_step_scaling_factor) const override{
const auto time_scaling_factor = this->computeAPosterioriTimeStepScalingFactorII();
return {time_scaling_factor.first,
        std::min(std::min(std::max(time_scaling_factor.second,
                                   this->minimal_time_step_scaling_factor),
                          this->maximal_time_step_scaling_factor),
                 current_time_step_scaling_factor)};
}

/*!
* \brief Update the internal energy at end of the time step
* \param[in] Psi_s: internal energy at end of the time step
*/
TFEL_HOST_DEVICE void computeInternalEnergy(stress& Psi_s) const
{
Psi_s=stress{0};
}

/*!
* \brief Update the dissipated energy at end of the time step
* \param[in] Psi_d: dissipated energy at end of the time step
*/
TFEL_HOST_DEVICE void computeDissipatedEnergy(stress& Psi_d) const
{
Psi_d=stress{0};
}

TFEL_HOST_DEVICE bool computeConsistentTangentOperator(const SMType smt){
using namespace std;
using namespace tfel::math;
using std::vector;
auto mfront_success = true;
TinyPermutation<2*StensorSize+2> jacobian_permutation;
if(!TinyMatrixSolve<2*StensorSize+2, NumericType, false>::decomp(this->jacobian,jacobian_permutation)){
return false;
}
struct TFEL_VISIBILITY_LOCAL GetPartialJacobianInvert{
TFEL_HOST_DEVICE GetPartialJacobianInvert(ModCamClay_semiExpl_coupled& mfront_behaviour_argument,
const tfel::math::TinyPermutation<2*StensorSize+2>& mfront_permutation_argument,
bool& mfront_success_argument)
: mfront_get_partial_jacobian_invert_behaviour(mfront_behaviour_argument),
mfront_get_partial_jacobian_invert_permutation(mfront_permutation_argument),
mfront_success_reference(mfront_success_argument){}
TFEL_HOST_DEVICE void operator()(tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7)){
this->mfront_success_reference = false;
}
}
TFEL_HOST_DEVICE void operator()(tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1)){
this->mfront_success_reference = false;
}
}
TFEL_HOST_DEVICE void operator()(tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A)){
this->mfront_success_reference = false;
}
}
TFEL_HOST_DEVICE void operator()(tfel::math::derivative_type<StressStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
tfel::math::derivative_type<StrainStensor, StrainStensor>& partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
tfel::math::derivative_type<real, StrainStensor>& partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A,
tfel::math::derivative_type<strain, StrainStensor>& partial_jacobian_rpc){
if(!this->mfront_get_partial_jacobian_invert_behaviour.computePartialJacobianInvert(this->mfront_get_partial_jacobian_invert_permutation, partial_jacobian_tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7,
partial_jacobian_tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1,
partial_jacobian_tfel_unicode_mangling_039Btfel_unicode_mangling_209A,
partial_jacobian_rpc)){
this->mfront_success_reference = false;
}
}
private:
ModCamClay_semiExpl_coupled& mfront_get_partial_jacobian_invert_behaviour;
const tfel::math::TinyPermutation<2*StensorSize+2>& mfront_get_partial_jacobian_invert_permutation;
bool& mfront_success_reference;
}; // end of struct GetPartialJacobianInvert
GetPartialJacobianInvert getPartialJacobianInvert(*this, jacobian_permutation, mfront_success);
#line 314 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
const auto tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38tfel_unicode_mangling_2215tfel_unicode_mangling_2202ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56 = [&](const auto ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56) {
#line 315 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
return (1.0 - (this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3) - (this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3))*((this->Stfel_unicode_mangling_1D38) < (1 - (this->Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3)) && (this->Stfel_unicode_mangling_1D38) > (this->Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3)
#line 316 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
? -(this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33) / ((this->ptfel_unicode_mangling_1D47) * (1 - (this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33))) * std::pow(
#line 317 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
std::pow(std::max(ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56, 0.0) / (this->ptfel_unicode_mangling_1D47),
#line 318 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
1.0 / (1.0 - (this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33))) +
#line 319 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
1.0,
#line 320 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
-(this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33) - 1) * std::pow(std::max(ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56, 0.0) / (this->ptfel_unicode_mangling_1D47),
#line 321 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
1.0 / (1.0 - (this->mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33)) - 1.0)
#line 322 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
: 0.);
#line 323 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
};
#line 324 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dtfel_unicode_mangling_03C3_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F  = - (this->tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47) * ((this->tfel_unicode_mangling_03C7) - ((this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) + (this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F)) * (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C7tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38) * tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38tfel_unicode_mangling_2215tfel_unicode_mangling_2202ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56(-((this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) + (this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F)))) * Stensor::Id() + (this->ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7) * (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C6tfel_unicode_mangling_2215tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38) * tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38tfel_unicode_mangling_2215tfel_unicode_mangling_2202ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56(-((this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) + (this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F))) * Stensor::Id();
#line 325 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
dtfel_unicode_mangling_03C3_ddT    = -3 * (this->K) * (this->tfel_unicode_mangling_03B1) * Stensor::Id();
#line 326 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
(this->dStfel_unicode_mangling_1D38_ddptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) = - tfel_unicode_mangling_2202Stfel_unicode_mangling_1D38tfel_unicode_mangling_2215tfel_unicode_mangling_2202ptfel_unicode_mangling_1D9Ctfel_unicode_mangling_1D43tfel_unicode_mangling_1D56( -((this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F) + (this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F)));
#line 328 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
if ((smt == ELASTIC) || (smt == SECANTOPERATOR))
#line 329 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 330 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
(this->dtfel_unicode_mangling_03C3_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52) = (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1);
#line 331 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 332 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else if (smt == CONSISTENTTANGENTOPERATOR)
#line 333 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 334 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
Stensor4 Je;
#line 335 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
getPartialJacobianInvert(Je);
#line 336 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
(this->dtfel_unicode_mangling_03C3_ddtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52) = (this->tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1) * Je;
#line 337 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
#line 338 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
else
#line 339 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
{
#line 340 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
return false;
#line 341 "/home/aqeel/ogs/MaterialLib/SolidModels/MFront/ModCamClay_semiExpl_coupled.mfront"
}
return mfront_success;
}

/*!
* \brief compute the sound velocity
* \param[in] rho_m0: mass density in the reference configuration
*/
TFEL_HOST_DEVICE speed computeSpeedOfSound(const massdensity&) const {
return speed(0);

}

TFEL_HOST_DEVICE const TangentOperator& getTangentOperator() const{
return this->Dt;
}

TFEL_HOST_DEVICE void updateExternalStateVariables(){
this->tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52  += this->dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52;
this->ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F  += this->dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F;
this->T += this->dT;
}

//!
~ModCamClay_semiExpl_coupled()
 override = default;

private:

TFEL_HOST_DEVICE std::pair<bool, real> computeAPrioriTimeStepScalingFactorII() const{
return {true, this->maximal_time_step_scaling_factor};
}

TFEL_HOST_DEVICE std::pair<bool, real> computeAPosterioriTimeStepScalingFactorII() const{
return {true,this->maximal_time_step_scaling_factor};
}

//! policy for treating out of bounds conditions
OutOfBoundsPolicy policy = tfel::material::None;

}; // end of ModCamClay_semiExpl_coupled class

template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
std::ostream&
operator <<(std::ostream& os,const ModCamClay_semiExpl_coupled<hypothesis, NumericType, false>& b)
{
os << "εᵗᵒ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 << '\n';
os << "Δεᵗᵒ : " << b.dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D57tfel_unicode_mangling_1D52 << '\n';
os << "σ : " << b.tfel_unicode_mangling_03C3 << '\n';
os << "pᴸᴿ : " << b.ptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F << '\n';
os << "Δpᴸᴿ : " << b.dptfel_unicode_mangling_1D38tfel_unicode_mangling_1D3F << '\n';
os << "Sᴸ : " << b.Stfel_unicode_mangling_1D38 << '\n';
os << "Δt : " << b.dt << '\n';
os << "ν : " << b.tfel_unicode_mangling_03BD << '\n';
os << "M : " << b.M << '\n';
os << "ka : " << b.ka << '\n';
os << "la : " << b.la << '\n';
os << "pc_char : " << b.pc_char << '\n';
os << "vʳ⁰ : " << b.vtfel_unicode_mangling_02B3tfel_unicode_mangling_2070 << '\n';
os << "α : " << b.tfel_unicode_mangling_03B1 << '\n';
os << "αᵇ : " << b.tfel_unicode_mangling_03B1tfel_unicode_mangling_1D47 << '\n';
os << "Sᴸʳ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_02B3 << '\n';
os << "Sᴳʳ : " << b.Stfel_unicode_mangling_1D33tfel_unicode_mangling_02B3 << '\n';
os << "pᵇ : " << b.ptfel_unicode_mangling_1D47 << '\n';
os << "mⱽᴳ : " << b.mtfel_unicode_mangling_2C7Dtfel_unicode_mangling_1D33 << '\n';
os << "bishop_type : " << b.bishop_type << '\n';
os << "bishop_value : " << b.bishop_value << '\n';
os << "pˢʷ : " << b.ptfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "mˢʷ : " << b.mtfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "Sᴸₗ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2097 << '\n';
os << "Sᴸₕ : " << b.Stfel_unicode_mangling_1D38tfel_unicode_mangling_2095 << '\n';
os << "σˢʷ : " << b.tfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "Δσˢʷ : " << b.dtfel_unicode_mangling_03C3tfel_unicode_mangling_02E2tfel_unicode_mangling_02B7 << '\n';
os << "εᵉˡ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 << '\n';
os << "Δεᵉˡ : " << b.dtfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 << '\n';
os << "Λₚ : " << b.tfel_unicode_mangling_039Btfel_unicode_mangling_209A << '\n';
os << "ΔΛₚ : " << b.dtfel_unicode_mangling_039Btfel_unicode_mangling_209A << '\n';
os << "pc : " << b.pc << '\n';
os << "εᵛₚₗ : " << b.tfel_unicode_mangling_03B5tfel_unicode_mangling_1D5Btfel_unicode_mangling_209Atfel_unicode_mangling_2097 << '\n';
os << "vʳ : " << b.vtfel_unicode_mangling_02B3 << '\n';
os << "T : " << b.T << '\n';
os << "ΔT : " << b.dT << '\n';
os << "σ₀ : " << b.tfel_unicode_mangling_03C3tfel_unicode_mangling_2080 << '\n';
os << "∂σ∕∂εᵉˡ : " << b.tfel_unicode_mangling_2202tfel_unicode_mangling_03C3tfel_unicode_mangling_2215tfel_unicode_mangling_2202tfel_unicode_mangling_03B5tfel_unicode_mangling_1D49tfel_unicode_mangling_02E1 << '\n';
os << "θ : " << b.theta << '\n';
os << "ε : " << b.epsilon << '\n';
os << "iterMax : " << b.iterMax << '\n';
os << "minimal_time_step_scaling_factor : " << b.minimal_time_step_scaling_factor << '\n';
os << "maximal_time_step_scaling_factor : " << b.maximal_time_step_scaling_factor << '\n';
os << "numerical_jacobian_epsilon : " << b.numerical_jacobian_epsilon << '\n';
return os;
}

/*!
* Partial specialisation for ModCamClay_semiExpl_coupled.
*/
template<ModellingHypothesis::Hypothesis hypothesis, typename NumericType>
class MechanicalBehaviourTraits<ModCamClay_semiExpl_coupled<hypothesis, NumericType, false> >
{
using size_type = unsigned short;
static constexpr unsigned short N = ModellingHypothesisToSpaceDimension<hypothesis>::value;
static constexpr unsigned short TVectorSize = N;
typedef tfel::math::StensorDimeToSize<N> StensorDimeToSize;
static constexpr unsigned short StensorSize = StensorDimeToSize::value;
typedef tfel::math::TensorDimeToSize<N> TensorDimeToSize;
static constexpr unsigned short TensorSize = TensorDimeToSize::value;
public:
static constexpr bool is_defined = true;
static constexpr bool use_quantities = false;
static constexpr bool hasStressFreeExpansion = false;
static constexpr bool handlesThermalExpansion = false;
static constexpr unsigned short dimension = N;
static constexpr size_type material_properties_nb = 18;
static constexpr size_type internal_variables_nb  = 2*StensorSize+4;
static constexpr size_type external_variables_nb  = 1;
static constexpr size_type external_variables_nb2 = 0;
static constexpr bool hasConsistentTangentOperator = true;
static constexpr bool isConsistentTangentOperatorSymmetric = false;
static constexpr bool hasPredictionOperator = false;
static constexpr bool hasAPrioriTimeStepScalingFactor = false;
static constexpr bool hasComputeInternalEnergy = false;
static constexpr bool hasComputeDissipatedEnergy = false;
/*!
* \return the name of the class.
*/
static const char* getName(){
return "ModCamClay_semiExpl_coupled";
}

};

} // end of namespace tfel::material

#endif /* LIB_TFELMATERIAL_MODCAMCLAY_SEMIEXPL_COUPLED_HXX */
